# Run with a directory generated by the independent Python reference.
using Test, Random, Statistics, JSON3
include(joinpath(@__DIR__,"..","scripts","run_mgmfrm_core_pilot.jl"))
const P=MGMFRMCorePilot
const B=P.B
root=first(ARGS)
output=length(ARGS)==2 ? ARGS[2] : joinpath(root,"julia-reference-verification.json")
records=NamedTuple[]

@testset "Independent dense MGMFRM DGP versus actual Julia target" begin
    for name in ("fixed","prior-1","prior-2","prior-3")
        observed=P.readjson(joinpath(root,name,"observed.json"))
        truth=P.readjson(joinpath(root,name,"truth.json"))
        spec=P.specification(observed);t=P.target(spec);q=Float64.(truth.raw)
        @test t.blueprint.parameter_names==String.(truth.raw_names)
        @test spec.data.person_levels==String.(truth.ordered_ids.person)
        direct=B._mgmfrm_source_constrained_params_from_unconstrained(t.design,q)
        probabilities=dropdims(B._mgmfrm_predictive_probabilities_direct(t.design,permutedims(direct));dims=1)
        logp=reduce(vcat,permutedims.(Vector{Float64}.(truth.log_probabilities)))
        expected=exp.(logp)
        @test probabilities≈expected atol=1e-12 rtol=1e-12
        @test B._source_fixture_logprior(t,q)≈truth.log_prior atol=1e-9
        @test B._source_fixture_loglikelihood(t,q)≈truth.log_likelihood atol=1e-8
        @test B.LogDensityProblems.logdensity(t,q)≈truth.log_likelihood+truth.log_prior atol=1e-8
        @test direct[101:105]≈truth.state.severity atol=1e-12
        @test direct[111:115]≈truth.state.loading atol=1e-12
        @test direct[116:120]≈truth.state.consistency atol=1e-12
        focal=P.focal_draws(t.design,permutedims(q))
        @test length(focal.names)==69 && length(unique(focal.names))==69
        @test count(==(:primary),focal.roles)==67
        p1=findfirst(==("P1"),spec.data.person_levels);p2=findfirst(==("P2"),spec.data.person_levels)
        for d in 1:2
            index=findfirst(==("theta[P1,D$d]-theta[P2,D$d]"),focal.names)
            @test focal.draws[1,index]≈truth.state.theta[p1][d]-truth.state.theta[p2][d]
            indices=findall(n->P.Q[spec.data.item[n],d],1:1250)
            for k in 1:4
                col=findfirst(==("mean_Pr[Y=$k,D$d,existing_panel]"),focal.names)
                @test focal.draws[1,col]≈mean(expected[indices,k]) atol=1e-12
            end
        end
        for i in 1:5, h in 1:3
            col=findfirst(==("step[I$i,h=$h]"),focal.names)
            @test focal.draws[1,col]≈truth.state.steps[i][h+1] atol=1e-12
        end
        push!(records,(;case=name,probability_error=maximum(abs.(probabilities-expected)),
            prior_error=abs(B._source_fixture_logprior(t,q)-truth.log_prior),
            likelihood_error=abs(B._source_fixture_loglikelihood(t,q)-truth.log_likelihood)))
    end
end

@testset "Core pilot precision and input boundaries without MCMC" begin
    rng=MersenneTwister(9220201)
    draws=hcat(randn(rng,2000),zeros(2000),.5 .+ .01randn(rng,2000))
    focal=(;names=["normal","constant","probability"],roles=[:primary,:primary,:primary],
        kinds=[:parameter,:parameter,:probability],draws)
    rows=P.precision_rows(focal)
    @test rows[1].local_precision_passed
    @test rows[3].local_precision_passed
    @test !rows[2].local_precision_passed && rows[2].mcse.mcse_status===:degenerate_draws
    @test getproperty.(rows[1].mcse.quantiles,:probability)==P.PROBS
    observed=JSON3.read(read(joinpath(root,"fixed","observed.json"),String),Dict{String,Any})
    observed["observations"][1]=copy(observed["observations"][2])
    @test_throws ErrorException P.specification(JSON3.read(JSON3.write(observed)))
    observed=JSON3.read(read(joinpath(root,"fixed","observed.json"),String),Dict{String,Any})
    for row in observed["observations"];row["score"]=4;end
    @test_throws ErrorException P.specification(JSON3.read(JSON3.write(observed)))
end

@testset "Core pilot does not qualify missing or bad sampler diagnostics" begin
    values=randn(MersenneTwister(9220202),4000,2)
    focal=(;names=["x","y"],draws=values)
    rows=B._candidate_mcmc_diagnostic_rows(values,focal.names,4;
        split_chains=true,rhat_threshold=1.01,ess_threshold=400.)
    sampler=[(;chain,n_nonfinite_logdensity=0,n_divergences=0,n_max_treedepth=0,e_bfmi=.5) for chain in 1:4]
    stats=fill((;numerical_error=false,n_steps=1,tree_depth=1,hamiltonian_energy=1.),4000)
    toy=(;diagnostic_surface=(;parameter_rows=rows,direct_parameter_rows=rows,sampler_rows=sampler),sampler_stats=stats)
    @test P.qualify(toy,focal).qualified
    @test !P.qualify(merge(toy,(;sampler_stats=stats[1:3999])),focal).qualified
    bad_sampler=[merge(r,(;e_bfmi=.1)) for r in sampler]
    @test !P.qualify(merge(toy,(;diagnostic_surface=merge(toy.diagnostic_surface,(;sampler_rows=bad_sampler)))),focal).qualified
    bad_sampler=[merge(r,(;n_max_treedepth=1)) for r in sampler]
    @test !P.qualify(merge(toy,(;diagnostic_surface=merge(toy.diagnostic_surface,(;sampler_rows=bad_sampler)))),focal).qualified
end

@testset "CmdStan follow-up refuses extra fits before sampling" begin
    mktempdir() do tmp
        contract=joinpath(tmp,"contract.json")
        observed=abspath(joinpath(root,"fixed","observed.json"))
        c=Dict("candidate_id"=>"independent_2d_raw_primary_01","maximum_fits"=>1,
            "planned_backends"=>["cmdstan"],"reuse_pilot"=>Dict(),"source_sha256"=>Dict(),
            "observed_path"=>observed,"observed_sha256"=>P.digest(observed))
        P.writejson(contract,c)
        @test first(P.checked_contract(contract)).maximum_fits==1
        @test_throws ErrorException P.fit_one(contract,:advancedhmc,tmp)
        @test !isfile(joinpath(tmp,"started.json"))
        c["planned_backends"]=["advancedhmc","cmdstan"]
        other=joinpath(tmp,"invalid.json");P.writejson(other,c)
        @test_throws ErrorException P.checked_contract(other)
    end
end

@testset "Batched focal probabilities preserve all draws and reject invalid batches" begin
    spec=P.specification(P.readjson(joinpath(root,"fixed","observed.json")))
    design=P.target(spec).design
    raw=.2randn(MersenneTwister(9220301),513,128)
    complete=P.focal_draws(design,raw;batch_size=513)
    for batch_size in (1,256,512,1024)
        batched=P.focal_draws(design,raw;batch_size)
        @test batched.names==complete.names && batched.roles==complete.roles && batched.kinds==complete.kinds
        @test batched.draws≈complete.draws atol=1e-14 rtol=1e-14
        @test size(batched.draws)==(513,69)
    end
    for batch_size in (0,-1,1.5,true)
        @test_throws ArgumentError P.focal_draws(design,raw;batch_size)
    end
    @test_throws ArgumentError P.focal_draws(design,zeros(0,128))
end

P.writejson(output,(;julia_version=string(VERSION),records,
    tests_passed=true,new_sampler_runs=0,new_native_stan_runs=0,scientific_acceptance=false))
