"""
    BayesianMGMFRM

Tools for validating long-format many-facet rating data, compiling MFRM-family
designs, fitting Bayesian models, and producing predictive, diagnostic, and
model-comparison summaries.

The stable fitting surface supports the documented MFRM/RSM/PCM configurations.
`BayesianMGMFRM.Experimental.fit(spec)` additionally supports a limited
partial-credit scalar GMFRM configuration and a fixed-Q, identity-correlation
confirmatory MGMFRM configuration. Unsupported generalized options are rejected
before numerical execution. The experimental namespace also provides
diagnostic operations for an exactly two-dimensional free-latent-correlation
density; that diagnostic surface has no fit result or cache integration and
does not establish replicated recovery.
"""
module BayesianMGMFRM

export FacetData,
    FacetDesign,
    FacetSpec,
    CmdStanError,
    GMFRMFit,
    MGMFRMFit,
    MFRMLogDensity,
    MFRMFit,
    MFRMPrior,
    ValidationIssue,
    ValidationReport,
    anchor_linking_summary,
    anchor_refit_plan,
    artifact_content_hash,
    benchmark_result_row,
    benchmark_summary,
    calibration_table,
    category_functioning_summary,
    constraint_table,
    coverage_matrix,
    coverage_summary,
    compare_models,
    compare_kfold,
    cached_fit,
    calibration_plot_data,
    case_study_provenance_manifest,
    comparison_evidence_row,
    comparison_evidence_summary,
    cmdstan_backend_contract,
    cmdstan_backend_check,
    conquest_bridge_bundle,
    diagnostic_map_data,
    design_identity,
    design_row_table,
    dff_report,
    domain_compilation_summary,
    evidence_metadata,
    evidence_artifact_schema_policy,
    external_bridge_result_receipt,
    expected_scores,
    facets_compatibility_stats,
    facets_bridge_bundle,
    facets_report,
    facet_response_table,
    fair_average_summary,
    falsification_rule_summary,
    falsification_rules,
    fit,
    fit_archive_manifest,
    fit_artifact,
    fit_cache_key,
    fit_metadata,
    fit_report,
    fit_report_health,
    fit_report_public,
    fit_report_dossier,
    fit_report_dossier_markdown,
    fit_report_markdown,
    fit_reproduction_manifest,
    fit_report_section,
    fit_report_sections,
    fit_report_rows,
    fit_ready_parameter_layout,
    fit_stats,
    getdesign,
    identification_declarations,
    diagnostics,
    initial_params,
    kfold,
    kfold_diagnostics,
    kfold_plan,
    kfold_plan_diagnostics,
    kfold_refit,
    kfold_refit_comparison,
    kfold_sensitivity_comparison,
    loglikelihood,
    loo,
    loo_diagnostics,
    loo_refit,
    loo_refit_comparison,
    loo_refit_plan,
    logposterior,
    logprior,
    linear_predictor_table,
    linear_predictor_values,
    local_dependence_calibration_contract,
    local_dependence_calibration_pilot_check,
    local_dependence_calibration_pilot_contract,
    local_dependence_calibration_pilot_preflight,
    local_dependence_calibration_row,
    local_dependence_calibration_summary,
    local_dependence_contract,
    local_dependence_simulation_grid,
    local_dependence_summary,
    model_equation,
    model_family_contract,
    mcmc_diagnostics,
    model_manifest,
    model_ladder,
    model_surface_check,
    model_surface_audit,
    mfrm_spec,
    parameter_block_diagnostics,
    parameter_recovery,
    parameter_recovery_plot_data,
    parameter_recovery_summary,
    pointwise_loglikelihood,
    pointwise_loglikelihood_matrix,
    posterior_predict,
    posterior_predictive_check,
    posterior_summary,
    psis_loo,
    prior_likelihood_sensitivity,
    predictive_check_summary,
    predictive_probabilities,
    predictive_residuals,
    predictive_standardized_residuals,
    predictive_variances,
    prior_predict,
    prior_predictive_check,
    q_matrix_validation,
    rater_diagnostics,
    rater_homogeneity_summary,
    rater_overlap,
    rating_design_check,
    rating_design_audit,
    related_software_capability_matrix,
    residual_summary,
    release_gate_check,
    release_scope_summary,
    load_conquest_semantic_parameters,
    load_fit_cache,
    load_fit_report_dossier,
    load_fit_report,
    load_fit_report_bundle,
    load_fit_report_tables,
    load_conquest_parameter_export,
    sampler_diagnostics,
    save_fit_cache,
    save_fit_report_dossier,
    save_fit_report_dossier_markdown,
    save_fit_report,
    save_fit_report_bundle,
    save_fit_report_markdown,
    save_fit_report_tables,
    save_external_bridge_bundle,
    sensitivity_comparison,
    sensitivity_comparison_summary,
    separation_reliability_summary,
    simulation_grid,
    simulation_grid_summary,
    simulate_local_dependence,
    simulate_responses,
    stan_validation_row,
    stan_validation_summary,
    threshold_map_data,
    testlet_design_check,
    testlet_design_audit,
    validate_design,
    validate_external_bridge_bundle,
    validation_suggestions,
    predictive_check_plot_data,
    wright_map_data,
    waic,
    waic_diagnostics

include("cmdstan_backend.jl")
include("evidence_metadata.jl")
include("facet_workflow.jl")
include("model_family_contract.jl")
include("model_contract.jl")
include("testlet_design_audit.jl")
include("bayesian_fit.jl")
include("cmdstan_fit.jl")
include("mgmfrm_free_correlation_candidate.jl")
include("mgmfrm_free_correlation_recovery.jl")
include("mgmfrm_free_correlation_study.jl")
include("mgmfrm_free_correlation_resource_probe.jl")
include("mgmfrm_free_correlation_study_scoring.jl")
include("experimental.jl")
include("anchor_refit_plan.jl")
include("facets_conquest_bridge.jl")
include("practitioner_diagnostics.jl")
include("local_dependence.jl")
include("local_dependence_known_truth_dgp.jl")
include("local_dependence_simulation.jl")
include("local_dependence_calibration.jl")
include("local_dependence_calibration_pilot.jl")

# Scalar validation target used by the analytic-gradient test suite.
include("scalar_validation_logp.jl")

end
