# Package-root API classifications for the 0.1.x compatibility line.
#
# This is an exact semantic boundary, not a source-file digest. Adding a root
# export requires choosing a stability class here and updating the public
# manual. Research helpers remain classified while they are retained at root
# for compatibility; new research work belongs outside the root namespace.

const _ROOT_API_STABLE_BINDINGS = (
    :CmdStanError,
    :FacetData,
    :FacetDesign,
    :FacetSpec,
    :MFRMFit,
    :MFRMLogDensity,
    :MFRMPrior,
    :ValidationIssue,
    :ValidationReport,
    :anchor_linking_summary,
    :anchor_refit_plan,
    :artifact_content_hash,
    :cached_fit,
    :calibration_plot_data,
    :calibration_table,
    :category_functioning_summary,
    :cmdstan_backend_check,
    :cmdstan_backend_contract,
    :compare_kfold,
    :compare_models,
    :conquest_bridge_bundle,
    :constraint_table,
    :coverage_matrix,
    :coverage_summary,
    :design_identity,
    :design_row_table,
    :dff_report,
    :diagnostic_map_data,
    :diagnostics,
    :domain_compilation_summary,
    :evidence_metadata,
    :expected_scores,
    :external_bridge_result_receipt,
    :facet_response_table,
    :facets_bridge_bundle,
    :facets_compatibility_stats,
    :facets_report,
    :fair_average_summary,
    :fit,
    :fit_archive_manifest,
    :fit_artifact,
    :fit_cache_key,
    :fit_metadata,
    :fit_ready_parameter_layout,
    :fit_report,
    :fit_report_dossier,
    :fit_report_dossier_markdown,
    :fit_report_health,
    :fit_report_markdown,
    :fit_report_public,
    :fit_report_rows,
    :fit_report_section,
    :fit_report_sections,
    :fit_reproduction_manifest,
    :fit_stats,
    :getdesign,
    :identification_declarations,
    :initial_params,
    :kfold,
    :kfold_diagnostics,
    :kfold_plan,
    :kfold_plan_diagnostics,
    :kfold_refit,
    :kfold_refit_comparison,
    :kfold_sensitivity_comparison,
    :linear_predictor_table,
    :linear_predictor_values,
    :load_conquest_parameter_export,
    :load_conquest_semantic_parameters,
    :load_fit_cache,
    :load_fit_report,
    :load_fit_report_bundle,
    :load_fit_report_dossier,
    :load_fit_report_tables,
    :local_dependence_contract,
    :local_dependence_summary,
    :loglikelihood,
    :logposterior,
    :logprior,
    :loo,
    :loo_diagnostics,
    :loo_refit,
    :loo_refit_comparison,
    :loo_refit_plan,
    :mcmc_diagnostics,
    :mfrm_spec,
    :model_equation,
    :model_family_contract,
    :model_ladder,
    :model_manifest,
    :model_surface_check,
    :ordinal_response_pattern_audit,
    :parameter_block_diagnostics,
    :pointwise_loglikelihood,
    :pointwise_loglikelihood_matrix,
    :posterior_mcse,
    :posterior_predict,
    :posterior_predictive_check,
    :posterior_summary,
    :predictive_check_plot_data,
    :predictive_check_summary,
    :predictive_probabilities,
    :predictive_residuals,
    :predictive_standardized_residuals,
    :predictive_variances,
    :prior_likelihood_sensitivity,
    :prior_predict,
    :prior_predictive_check,
    :psis_loo,
    :q_matrix_validation,
    :rater_diagnostics,
    :rater_homogeneity_summary,
    :rater_overlap,
    :rating_design_check,
    :related_software_capability_matrix,
    :residual_summary,
    :sampler_diagnostics,
    :save_external_bridge_bundle,
    :save_fit_cache,
    :save_fit_report,
    :save_fit_report_bundle,
    :save_fit_report_dossier,
    :save_fit_report_dossier_markdown,
    :save_fit_report_markdown,
    :save_fit_report_tables,
    :sensitivity_comparison,
    :sensitivity_comparison_summary,
    :separation_reliability_summary,
    :simulate_responses,
    :testlet_design_check,
    :threshold_map_data,
    :validate_design,
    :validate_external_bridge_bundle,
    :validation_suggestions,
    :waic,
    :waic_diagnostics,
    :wright_map_data,
)

const _ROOT_API_COMPATIBILITY_BINDINGS = (
    :GMFRMFit,
    :MGMFRMFit,
    :model_surface_audit,
    :rating_design_audit,
    :testlet_design_audit,
)

const _ROOT_API_RESEARCH_BINDINGS = (
    :benchmark_result_row,
    :benchmark_summary,
    :case_study_provenance_manifest,
    :comparison_evidence_row,
    :comparison_evidence_summary,
    :evidence_artifact_schema_policy,
    :falsification_rule_summary,
    :falsification_rules,
    :local_dependence_calibration_contract,
    :local_dependence_calibration_pilot_check,
    :local_dependence_calibration_pilot_contract,
    :local_dependence_calibration_pilot_preflight,
    :local_dependence_calibration_row,
    :local_dependence_calibration_summary,
    :local_dependence_simulation_grid,
    :mgmfrm_decision_stability_score,
    :mgmfrm_predictive_recovery_score,
    :mgmfrm_response_stress_fit_attempts,
    :mgmfrm_response_stress_plan,
    :mgmfrm_response_stress_preflight,
    :mgmfrm_validation_analysis_contract,
    :mgmfrm_validation_execution_design_contract,
    :mgmfrm_validation_isolated_resource_probe,
    :mgmfrm_validation_isolated_resource_review,
    :mgmfrm_validation_primary_grid_candidates,
    :mgmfrm_validation_primary_grid_preflight,
    :mgmfrm_validation_primary_resource_plan,
    :mgmfrm_validation_protocol,
    :mgmfrm_validation_replication_precision,
    :mgmfrm_validation_resource_probe,
    :mgmfrm_validation_scaled_resource_plan,
    :mgmfrm_validation_short_nuts_resource_probe,
    :parameter_recovery,
    :parameter_recovery_plot_data,
    :parameter_recovery_summary,
    :release_gate_check,
    :release_scope_summary,
    :simulate_local_dependence,
    :simulate_mgmfrm_response_stress,
    :simulate_mgmfrm_validation_primary_candidate,
    :simulation_grid,
    :simulation_grid_summary,
    :stan_validation_row,
    :stan_validation_summary,
)

function _root_api_contract()
    return (;
        schema = "bayesianmgmfrm.root_api_contract.v1",
        release_line = "0.1.x",
        growth_policy = :frozen,
        owner = :package_maintainers,
        manual_policy = (;
            stable = :required,
            compatibility = :required_with_migration_guidance,
            research = :optional_explicitly_nonstable,
        ),
        stable = _ROOT_API_STABLE_BINDINGS,
        compatibility = _ROOT_API_COMPATIBILITY_BINDINGS,
        research = _ROOT_API_RESEARCH_BINDINGS,
    )
end
